---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch