---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    url: https://$(HOST):9443/mutate-v1beta1-hostedcluster
  failurePolicy: Fail
  name: mhostedcluster.kb.io
  rules:
  - apiGroups:
    - hypershift.openshift.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hostedclusters
  sideEffects: None
